# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Orchestrate or schedule a set of jobs
orbs:
  aws-cli: circleci/aws-cli@2.0.2
commands:
  print_pipeline_id:
    steps:
      - run: echo "[all]" >inventory
jobs:
  myjob:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: example
      - run: aws ec2 describe-instances  --query 'Reservations[*].Instances[*].PublicIpAddress'  --filters "Name=tag:Name,Values=Balakrishna Avula" --output text >> inventory
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
              - inventory
      - run: cat inventory
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - myjob
